---
title: "Figure 1A — Phylogenetic distribution of the 96 sequenced strains"
author: "Akriti | Gresham Lab, NYU"
output: html_document
---

Phylogenetic tree of the 1011 *S. cerevisiae* collection (Peter et al. 2018),
with the 96 strains used in this study marked as red tip points. Branches are
coloured by clade assignment.

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r libraries}
library(ggplot2)
library(ggtree)
library(viridis)
library(dplyr)
```

```{r load}
# tree1011  : phylo object for the 1011 collection
# cladesdf  : per-strain metadata (STD_name, clades)
load("../data/1011_tree_assets.RData")
```

```{r strains}
strains_96 <- c(
  "BNV", "BQM", "ALS", "CAE", "CGS", "AQA", "CDT", "BRK", "BHM", "AMP",
  "BHK", "BTT", "CNK", "CNH", "BVG", "BBQ", "BFP", "BTG", "CLB", "BFH",
  "BGD", "BGF", "BGE", "BDN", "CBN", "CFF", "SACE_YAG", "SACE_YCF", "BDB", "BHG",
  "SACE_MAA", "AFE", "ATS", "ATR", "AAP", "BDL", "CPI", "CPK", "CPN", "BDQ",
  "BNC", "BMV", "BDP", "BCK", "CBL", "AKI", "SACE_YCE", "CDE", "SACE_YBJ", "ANN",
  "CQD", "CQF", "APQ", "AKH", "BAF", "BAM", "BAQ", "BAG", "BAL", "CEG",
  "CCQ", "CCR", "CCS", "SACE_YCR", "BAK", "BAI", "CCN", "CDL", "BMA", "AKM",
  "BMB", "BMC", "SACE_YCY", "BAN", "BAP", "CCD", "CCG", "CDF", "CDH", "CDI",
  "AVI", "ANH", "ANG", "SACE_YCU", "CCV", "SACE_YCM", "SACE_YDE", "CLI", "CLN", "CMI",
  "CLP", "CGL", "CGN", "BHQ", "BEF", "SACE_YCK"
)

stopifnot(length(strains_96) == 96)

cladesdf <- cladesdf %>%
  mutate(highlight = ifelse(STD_name %in% strains_96, "In subset", "Not in subset"))

# sanity check: all 96 present in the tree metadata
setdiff(strains_96, cladesdf$STD_name)
```

```{r colours}
# clade colours from viridis; subset tips red, all other tips invisible
cols <- c(viridis(length(unique(cladesdf$clades))),
          "In subset"     = "red",
          "Not in subset" = "transparent")
names(cols) <- c(unique(cladesdf$clades), "In subset", "Not in subset")
```

```{r figure, fig.width = 14, fig.height = 8}
fig1A <- ggtree(tree1011,
                layout      = "ape",
                open.angle  = 10,
                size        = 0.2,
                aes(color = clades)) %<+% cladesdf +
  geom_tippoint(aes(color = highlight), size = 2) +
  scale_color_manual(
    values = cols,
    breaks = unique(cladesdf$clades),   # legend shows clades only
    name   = "Clade"
  ) +
  guides(color = guide_legend(
    override.aes = list(size = 3, linewidth = 1),
    ncol = 2
  )) +
  theme(
    legend.position   = "right",
    legend.text       = element_text(size = 14),
    legend.title      = element_text(size = 14, face = "bold"),
    legend.background = element_blank(),
    panel.grid.major  = element_blank(),
    panel.grid.minor  = element_blank(),
    panel.background  = element_rect(fill = "transparent", colour = NA),
    plot.background   = element_rect(fill = "transparent", colour = NA)
  )

fig1A
```

```{r save}
ggsave("../results/tree_with_96_strain.tiff", plot = fig1A,
       width = 14, height = 8, dpi = 300,
       device = "tiff", compression = "lzw")
```

